### ISSUE TITLE
Disable golden sword dropped by zombified piglin

### ISSUE THREAD

**Issue by NoltoxGit** [Rosewood-Development/RoseLoot#24]
Hello !
How is it possible to disable the loot of the golden sword by zombified piglins please ?

I can't find anything for it in the game's default file :/
```yml
type: ENTITY
overwrite-existing: items
conditions:
  - 'entity-type:zombified_piglin'
pools:
  0:
    conditions: []
    rolls: 1
    bonus-rolls: 0
    entries:
      0:
        conditions: []
        items:
          0:
            type: item
            item: rotten_flesh
            amount:
              min: 0
              max: 1
            enchantment-bonus:
              enchantment: looting
              bonus-per-level:
                min: 0
                max: 1
  1:
    conditions: []
    rolls: 1
    bonus-rolls: 0
    entries:
      0:
        conditions: []
        items:
          0:
            type: item
            item: gold_nugget
            amount:
              min: 0
              max: 1
            enchantment-bonus:
              enchantment: looting
              bonus-per-level:
                min: 0
                max: 1
  2:
    conditions:
      - 'killed-by:player'
      - 'enchantment-chance:2.5%,looting,1%'
    rolls: 1
    bonus-rolls: 0
    entries:
      0:
        conditions: []
        items:
          0:
            type: item
            item: gold_ingot
  3:
    conditions: []
    rolls: 1
    bonus-rolls: 0
    entries:
      0:
        conditions: []
        items:
          0:
            type: entity_equipment
```
